### ISSUE TITLE
Not able to add the integration. 

### ISSUE THREAD

**Issue by Cerbone** [swartjean/ha-eskom-loadshedding#1]
Used HACS to do the download however when trying to complete the last step (adding the integration). It simply exits upon clicking the eskom integration. 

```

**Comment by swartjean** [comment]
I will take a look at this ASAP. I have not been able to test adding the integration via the default repos in HACS since it just got added, but it looks like it got lost again in the PR for one of my other integrations.

I'll get it added back again and see if I can replicate what you are seeing.

**Comment by swartjean** [comment]
@Cerbone the integration is now added back to HACS, could you please uninstall the integration, restart your Home Assistant instance, and go through the install procedure again?

I have just tested installing the integration again and it seems to work as expected.

**Comment by w1tw0lf** [comment]
Having the same issues on my side.

**Comment by swartjean** [comment]
@w1tw0lf can you please check your Home Assistant logs for any errors or warnings from the integration and share them here?

Please also share your Home Assistant and HACS versions.

I will do some more testing this evening.

**Comment by w1tw0lf** [comment]
```
Log Details (ERROR)
Logger: homeassistant.config_entries
Source: config_entries.py:531
First occurred: 2:16:50 PM (1 occurrences)
Last logged: 2:16:50 PM

Error occurred loading configuration flow for integration eskom_loadshedding: No module named 'aiohttp_retry'
```

**Comment by swartjean** [comment]
> ```
> Log Details (ERROR)
> Logger: homeassistant.config_entries
> Source: config_entries.py:531
> First occurred: 2:16:50 PM (1 occurrences)
> Last logged: 2:16:50 PM
> 
> Error occurred loading configuration flow for integration eskom_loadshedding: No module named 'aiohttp_retry'
> ```

Thanks for this. I did something illegal with the `aiohttp_retry` requirement here. I will address it this evening :+1:

**Comment by w1tw0lf** [comment]
Perfect. Great to see some local integrations for HA

**Comment by swartjean** [comment]
@Cerbone @w1tw0lf - I have released v1.0.1 that should address this problem, I've tested it on a clean build and it seems to work now. 

You should be able to update in HACS, restart HA, and add the integration. Let me know if it works for you.

Thanks for the feedback, it's always nice to see some fellow South Africans in the wild 👋

**Comment by w1tw0lf** [comment]
Awesome !

Working perfectly on myside.

**Comment by swartjean** [comment]
Great! If @Cerbone can confirm it works I will close this issue.

**Comment by Cerbone** [comment]
@swartjean works like a charm. Now I just need to wait for load-shedding to be implemented to see if it updates from 0.
