### ISSUE TITLE
Set Frequency

### ISSUE THREAD

**Issue by shaundekok** [swartjean/ha-eskom-loadshedding#13]
Give the ability to change the frequency, perhaps set it to start on the hour or 1 minute past. Often load shedding starts and HA is only updated 15 minutes or so afterwards with the change.

**Comment by swartjean** [comment]
The integration has been overhauled to use the EskomSePush API (#19). The update frequency can be configured via the integration configuration but the recommended way to automate around loadshedding is to use calendar triggers on upcoming events. See the new README for an example.
