### ISSUE TITLE
Ha- City Of Cape Town Loadshedding

### ISSUE THREAD

**Issue by Surgical17** [swartjean/ha-eskom-loadshedding#14]
Hi Swartjean

Is it possible that you can create the same integration for City of Cape Town to read data from their API?
https://www.capetown.gov.za/Family%20and%20home/Residential-utility-services/Residential-electricity-services/Load-shedding-and-outages

This will help alot as they tend to have different stages of load shedding.

If I knew how I would have done it XD

Thanx

**Comment by cliffordwhansen** [comment]
@Surgical17 Unfortunatly they don't have an API it's links to PDF pages.

I'm not saying it can't be done, just it's not as simple since there is no API

**Comment by biovolt** [comment]
Tiaanv added this feature. Maybe you can ask tiaanv to add a pull request? 

https://github.com/tiaanv/ha-eskom-loadshedding

**Comment by swartjean** [comment]
This has been added. Please see #19.
