### ISSUE TITLE
Integration ISSUE

### ISSUE THREAD

**Issue by tunavis** [swartjean/ha-eskom-loadshedding#18]
Experiencing this issue have no idea of what it might be? Screenshot below:
![5ac4d84d0745e_thumb900](https://user-images.githubusercontent.com/8057000/162923551-141f9968-2c45-4aab-ab08-689ec4e60ea1.jpg)

**Comment by cliffordwhansen** [comment]
Do you see anything in the logs?
Have you tried to remove, restart and readd it?

**Comment by geeneo** [comment]
Seems broken with 05/2022 update.  :(  

![image](https://user-images.githubusercontent.com/49159962/167101603-efbaba7c-3935-4358-9560-18022857c853.png)

**Comment by cliffordwhansen** [comment]
The eskom site had a certificate issue this morning (expired), and the site is currently not available (hopefully they installing a new cert)

**Comment by cliffordwhansen** [comment]
@geeneo I see the certificate has been updated now and intergration seems to be loading again

**Comment by geeneo** [comment]
Thx  Clifford working again !  :)

**Comment by swartjean** [comment]
Closing this, see #19.
