### ISSUE TITLE
Eskom Se Push Business API

### ISSUE THREAD

**Issue by brad55590** [swartjean/ha-eskom-loadshedding#19]
Would be nice to integrate this with the Eskom Se Push Business API in order to get the current stage, co-ordinate identification, as well as up-to-date schedules

**Comment by fjordaan00711** [comment]
Same here

**Comment by cliffordwhansen** [comment]
I have contacted EskomSePush to request access, will update this issue with any responses I get from them. _holding thumbs_

For transparency the email:
```
Hi Herman/Dan,

First off, thank you for EskomSePush, it has been an amazing help.

There is a custom component for HomeAssistant (https://home-assistant.io) on GitHub (https://github.com/swartjean/ha-eskom-loadshedding) which tells us the current level.

We would like to use the EskomSePush Business API to enhance this custom component, so that we can set up automations based on the current schedules. (for shutting down things before the power goes out)

We have an issue (https://github.com/swartjean/ha-eskom-loadshedding/issues/19) to keep track of this request.

Thank you,
Clifford.
```

**Comment by wernerhp** [comment]
I've also inquired with ESP to add it to my own HA Integration.  Their Business API is currently only targeted at larger businesses as it comes with a hefty price tag.  In future a Public API may become available.  

In the meantime, I've created [this Python library](https://gitlab.com/wernerhp/load-shedding) which wraps the Eskom API and does some caching.  I use it in my own HA Integration, but of course it has it's limitations that it only supports Eskom Direct.  If anyone wants to collaborate and add other Providers, please do so.  It will be nice to have a single library to get any schedule.

**Comment by cliffordwhansen** [comment]
Thanks @wernerhp will be great to have a single library, less duplication of code/resources

**Comment by MohammedHoosen** [comment]
Looks ESP making it available for personal use. Check their post here:
https://www.linkedin.com/pulse/your-business-impacted-outages-introducing-api-dan-wells%3FtrackingId=qhc198dHQ8uBqj%252Bznt1kwQ%253D%253D/?trackingId=qhc198dHQ8uBqj%2Bznt1kwQ%3D%3D

You can request access here
https://docs.google.com/forms/d/e/1FAIpQLSeZhAkhDaQX_mLT2xn41TkVjLkOH3Py3YWHi_UqQP4niOY01g/viewform?usp=sf_link

API Docs
https://documenter.getpostman.com/view/1296288/UzQuNk3E

**Comment by cliffordwhansen** [comment]
Awesome find, thanks @MohammedHoosen 

#edit: Requested my key (holds thumbs)
#edit2: Got a key and it works nicely :-)

**Comment by swartjean** [comment]
@MohammedHoosen thanks for this! That is awesome news.

I have gone through their API docs and it looks like it has everything necessary to put together a really useful integration.

I should have some time soon, so I'll start working on a V2 update for this integration that switches over to the ESP API 👍 Each user will obviously have to request their own token from ESP to avoid abuse and quota restrictions. I'll continue to track progress under this issue.

**Comment by reganerasmus** [comment]
Wow, just read this about the ESP API, that would be incredible as i have always wanted specific automations that kick off when load-shedding hits my specific area - you a legend man

**Comment by reganerasmus** [comment]
I have also requested my ESP API token in the meanwhile

**Comment by swartjean** [comment]
An update on this - I've implemented the configuration flow for the ESP API token validation and area lookup and it seems to be working well.

I just need to break the available data out into a couple of new sensors and then I will get a new release out. Should be this weekend if I have time.

One thing to note is that ESP seems to provide a quota of 50 queries per day by default. Loadshedding status queries (national and COCT loadshedding stages) and area information queries (local loadshedding stage/schedule for your area) count as 1 query each, while the area lookup which is required during configuration counts as 5 queries. This means that we will have to be a bit frugal with update intervals to avoid having everyone exceed their quotas. I will choose some conservative defaults and make this configurable.

**Comment by swartjean** [comment]
Let me know if there are any glaring issues, I've only been able to do limited testing due to the lack of CoCT loadshedding recently 👍
