### ISSUE TITLE
Installed but no sensor or errors

### ISSUE THREAD

**Issue by parautenbach** [swartjean/ha-eskom-loadshedding#2]
## Version of the custom_component
1.0.1 (and HA 0.114.1)

## Configuration

Installed via HACS (and rebooted several times). I've checked that all the files are there:
```
-rw-r--r-- 1 homeassistant homeassistant 2795 Sep 12 10:42 config_flow.py
-rw-r--r-- 1 homeassistant homeassistant  849 Sep 12 10:42 const.py
-rw-r--r-- 1 homeassistant homeassistant 1439 Sep 12 10:42 entity.py
-rw-r--r-- 1 homeassistant homeassistant 2770 Sep 12 10:42 eskom_interface.py
-rw-r--r-- 1 homeassistant homeassistant 3076 Sep 12 10:42 __init__.py
-rw-r--r-- 1 homeassistant homeassistant  360 Sep 12 10:42 manifest.json
-rw-r--r-- 1 homeassistant homeassistant  799 Sep 12 10:42 sensor.py
-rw-r--r-- 1 homeassistant homeassistant  234 Sep 12 10:42 strings.json
drwxr-xr-x 2 homeassistant homeassistant 4096 Sep 12 10:42 translations
```

HACS still shows it as installed but it doesn't show as an integration under the server's integrations section (not sure if it should). Clicking + and searching for it doesn't yield anything either.

## Describe the bug

No sensor is created. 

## Debug log

Debug logging is on:
```yaml
logger:
  default: warning
  logs:
    custom_components.eskom_loadshedding: debug
```

But this is all I get:
```text
2020-09-12 11:03:23 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for eskom_loadshedding which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
```

**Comment by ipodmusicman** [comment]
You need to click the + to add the integration in HA.  I've just done it now.

**Comment by parautenbach** [comment]
I did, but it wasn't showing up. Just restarted HA again and now it's showing. Thanks.

**Comment by swartjean** [comment]
@parautenbach glad you got it sorted, and thanks for assisting @ipodmusicman 👍

**Comment by parautenbach** [comment]
Now it's doing this (the error repeating and there's also an API backoff message):
```
2020-09-12 17:33:35 INFO (MainThread) [custom_components.eskom_loadshedding]
-------------------------------------------------------------------
Eskom Loadshedding Interface
Version: 1.0.1
Welcome to the Eskom Loadshedding Interface!
If you have any issues with this you need to open an issue here:
https://github.com/swartjean/ha-eskom-loadshedding/issues
-------------------------------------------------------------------
2020-09-12 17:33:46 ERROR (MainThread) [homeassistant] Error doing job: SSL handshake failed
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 625, in _on_handshake_complete
    raise handshake_exc
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "/usr/lib/python3.7/ssl.py", line 763, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1056)
2020-09-12 17:33:46 ERROR (MainThread) [homeassistant] Error doing job: SSL error in data received
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "/usr/lib/python3.7/ssl.py", line 763, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:1056)
```

**Comment by parautenbach** [comment]
It seems to struggle to complete the installation (due to those errors perhaps):

![Screenshot 2020-09-12 at 17 38 51](https://user-images.githubusercontent.com/743320/92999131-df283680-f51e-11ea-92e5-05c82dda3dd1.png)

**Comment by parautenbach** [comment]
Something's definitely not right: It seems to create multiple platforms or something.

![Screenshot 2020-09-12 at 17 42 00](https://user-images.githubusercontent.com/743320/92999229-85743c00-f51f-11ea-8638-db2fb1570878.png)

**Comment by parautenbach** [comment]
@ipodmusicman which version of HA are you on and did you install via HACS or manually?

**Comment by swartjean** [comment]
That's very strange, I can't say that I've ever seen this happen before. Which platform are you running HA on?

**Comment by ipodmusicman** [comment]
I’m running the latest version. 0.114.3 and I installed via HACS.
Installed the component via HACS
Restarted HA
Added the integration and the sensor was there. No problem at all.

**Comment by parautenbach** [comment]
@swartjean it's HA core running an a Pi in a venv.

**Comment by swartjean** [comment]
Strange. I'll look into it and try do some tests, but at this point I can't say for sure that it's a problem with the integration specifically. Will update if I find anything.

Are you connecting to HA using SSL?

**Comment by parautenbach** [comment]
I'll also try tomorrow to see if I can learn anything else that could help. 

I do use NabuCasa but I was on wifi on my home network when I set it up. 

Is the connection to the Eskom API over HTTPS?

**Comment by parautenbach** [comment]
Did a reboot and clean install of the integration via HACS:
* no sensor created after configuring the integration (the config flow just hangs with no debug output)
* repeated SSL errors in logs 

I'd be happy to try any suggestions or to provide more info.

**Comment by swartjean** [comment]
@parautenbach I spun up a test instance on a VM with HA installed in a Python 3.7 venv. I am (strangely) happy to say that I am seeing some of the same issues that you are. 

The first time I attempted to install the integration it just hung indefinitely on the "Please wait" spinner, and after refreshing, deleting, and re-adding the integration, I also saw the error with multiple platforms being added.

However, I am not seeing the SSL errors in any shape or form. It is possible that these are unrelated to the integration (in your log it does not look like the SSL errors trace back to this custom component), but let's not rule anything out.

At least now I can work through this and figure out why things are not behaving when running in this configuration.

**Comment by swartjean** [comment]
@parautenbach I just merged a PR that I am quite sure will address this issue, but I am going to reopen it so that you can confirm.

Basically what has happened is that "newer" versions of Debian have raised the minimum security level for SSL. ([1](https://wiki.debian.org/ContinuousIntegration/TriagingTips/openssl-1.1.1), [2](https://github.com/psf/requests/issues/4775)) From what I can tell, Eskom doesn't seem to meet all of these requirements on their loadshedding API.

Best case scenario, Eskom would update the certificate on their loadshedding domain. I'm not even going to bother getting in touch with them about this.

I've implemented a new SSL context which gets applied to requests to the Eskom API. This lowers the required security level and everything should now work as expected. 

You should now be able to update to v1.0.2 in HACS, restart HA, and install the integration. Let me know how it works out.

**Comment by parautenbach** [comment]
@swartjean I updated to v1.0.2 last night and there were no problems: the sensor was created. Thanks for the quick turnaround time. 

Thanks for the SSL explanation. I agree that contacting Eskom would probably be futile. 

Not related to the issue but are you planning on adding more features such as a sensor for one's specific area? I know the Eskom data is (apparently) quite messy but it could be a nice feature. One of my colleagues is one of the people that built Eskom se Push if you'd like to get in touch with someone that's familiar with the data.

**Comment by swartjean** [comment]
> Not related to the issue but are you planning on adding more features such as a sensor for one's specific area? I know the Eskom data is (apparently) quite messy but it could be a nice feature. One of my colleagues is one of the people that built Eskom se Push if you'd like to get in touch with someone that's familiar with the data.

Yes, this is something I definitely will be implementing. Ideally I would like to be able to provide zone and schedule information based on the location configured in your HA instance. The Eskom API already supports lookups for suburbs and schedules, but unfortunately only for Eskom-supplied areas. This just means that many metropolitan areas will be unsupported if the Eskom API is the sole datasource.

It looks like the guys at ESP have gotten very good at aggregating data from the various city/provincial websites, so it could be cool to chat sometime. I've followed you and might ping you about it in the future 👍
