### ISSUE TITLE
Not allowing installation 

### ISSUE THREAD

**Issue by StanderHome** [swartjean/ha-eskom-loadshedding#28]
Just tried the instalation. Thanks for opening up an integration rather tha  trying to figure out API for newbies...

Once I add the integration it brings up a block to submit something. Its not staying what it needs. I assumed your Key from ESP but if I enter and submit it just blanks it out and I need to re-enter.

I cannot get any further

**Comment by swartjean** [comment]
Hi, that's a bit strange. I wonder if it isn't a translation/localization issue. Is your home assistant configured for English? 

The first text block should be your API token yes. If it blanks it out it should be because the token wasn't valid or maybe had run out of quota for the day. Is this a new token from their Gumroad site?

The second text box would be for your area, after which you should see a list of areas to choose from.

**Comment by StanderHome** [comment]
Hey Jean

Thanks for this.
After I added the issue I kept on trying to see what was happening and what the issues are.

I finally got it right where it showed the area but I tested it with the wrong info. I then had to wait 1 more day before I could action the area again as it just came up with an error the whole time.

All good now though, so I am a happy chappy. Its works brilliantly.

Is there a way to set the check to be hourly? Or will that throw out the number of pings you have available on the free API


[Logo]<https://www.theaccountrepreneur.co.za/>
Shaan Stander CA(SA)
Director
mobile: 073 460 6350
email: ***@***.******@***.***>
[Facebook icon]<https://web.facebook.com/TheAccountrepreneur/>  [LinkedIn icon] <https://www.linkedin.com/in/shaan-stander-ca-sa-a0925896/>   [Google Plus icon] <https://www.theaccountrepreneur.co.za/>
Disclaimer Statement:
This e-mail and any file transmitted with it contain confidential information, which is intended only for use by the addressee. If you have received this e-mail in error then copying, distributing, disclosing or otherwise acting in reliance upon this e-mail is strictly prohibited. If you have received this message in error, please notify The Accountrepreneur immediately.
Any views expressed in this message are those of the individual sender and The Accountrepreneur accepts no liability for the content of this message except where the sender specifically states them to be the views of The Accountrepreneur.

**Comment by StanderHome** [comment]
Hi Jean

Hope all is well.

The last 3 days or so I dont get any updates.  Is it on the App side or the integration? Is yours fine

**Comment by swartjean** [comment]
Hey there, that is weird - mine seems to be working fine. My sensor has been updating today and the my test automations seem to have been firing. What is your API quota sensor reporting?

**Comment by StanderHome** [comment]
HI Jean

It was quite strange.
It all started up again yesterday and seems to be working fine now

Thanks for the response


[Logo]<https://www.theaccountrepreneur.co.za/>
Shaan Stander CA(SA)
Director
mobile: 073 460 6350
email: ***@***.******@***.***>
[Facebook icon]<https://web.facebook.com/TheAccountrepreneur/>  [LinkedIn icon] <https://www.linkedin.com/in/shaan-stander-ca-sa-a0925896/>   [Google Plus icon] <https://www.theaccountrepreneur.co.za/>
Disclaimer Statement:
This e-mail and any file transmitted with it contain confidential information, which is intended only for use by the addressee. If you have received this e-mail in error then copying, distributing, disclosing or otherwise acting in reliance upon this e-mail is strictly prohibited. If you have received this message in error, please notify The Accountrepreneur immediately.
Any views expressed in this message are those of the individual sender and The Accountrepreneur accepts no liability for the content of this message except where the sender specifically states them to be the views of The Accountrepreneur.

**Comment by dharmeshbhana** [comment]
Hi there,

A bit of a novice on HA. I followed your steps, created Eskom LS folder under custom config, downloaded all the files and one folder from github (custom_components/eskom_loadshedding) and uploaded.

Restarted HA

But cant find it under integrations when I search for it. Any ideas please? Am i missing a step?

**Comment by dharmeshbhana** [comment]
Also tried via HACS - installed Eskom load shedding interface. Shows up under custom config folder, but dosent allow to proceed to UI...

**Comment by StanderHome** [comment]
Hi there

Happy to assist with this if youd like,

Send me your number. A call might be easier


[Logo]<https://www.theaccountrepreneur.co.za/>
Shaan Stander CA(SA)
Director
mobile: 073 460 6350
email: ***@***.******@***.***>
[Facebook icon]<https://web.facebook.com/TheAccountrepreneur/>  [LinkedIn icon] <https://www.linkedin.com/in/shaan-stander-ca-sa-a0925896/>   [Google Plus icon] <https://www.theaccountrepreneur.co.za/>
Disclaimer Statement:
This e-mail and any file transmitted with it contain confidential information, which is intended only for use by the addressee. If you have received this e-mail in error then copying, distributing, disclosing or otherwise acting in reliance upon this e-mail is strictly prohibited. If you have received this message in error, please notify The Accountrepreneur immediately.
Any views expressed in this message are those of the individual sender and The Accountrepreneur accepts no liability for the content of this message except where the sender specifically states them to be the views of The Accountrepreneur.

**Comment by dharmeshbhana** [comment]
Thanks.

Sorted....

**Comment by StanderHome** [comment]
I have mine hooked up to my solar so it can push batteries to start force charge if below a certain %, 2 hours before loadshedding in Home Assistant, backing up with Solar Assistant…

Quite nifty to have the ESP pull in to make the above happen.

Have a lekker week


[Logo]<https://www.theaccountrepreneur.co.za/>
Shaan Stander CA(SA)
Director
mobile: 073 460 6350
email: ***@***.******@***.***>
[Facebook icon]<https://web.facebook.com/TheAccountrepreneur/>  [LinkedIn icon] <https://www.linkedin.com/in/shaan-stander-ca-sa-a0925896/>   [Google Plus icon] <https://www.theaccountrepreneur.co.za/>
Disclaimer Statement:
This e-mail and any file transmitted with it contain confidential information, which is intended only for use by the addressee. If you have received this e-mail in error then copying, distributing, disclosing or otherwise acting in reliance upon this e-mail is strictly prohibited. If you have received this message in error, please notify The Accountrepreneur immediately.
Any views expressed in this message are those of the individual sender and The Accountrepreneur accepts no liability for the content of this message except where the sender specifically states them to be the views of The Accountrepreneur.

**Comment by dharmeshbhana** [comment]
Thanks

Thanks, interesting. I wanted to do the same with SUnsynk inverter but at
this point I cannot get data.API for that. Suppose go to go the Solar
assistant route.

Maybe question your integration. I'm using NodeRed for automations and
trying to get  the future next load shedding time so I can run some
automations. I see it shows up on the calendar but there isn't entity that
states next load shedding time? Unless I am not reading it correctly.

Thanks

**Comment by swartjean** [comment]
Hi @dharmeshbhana, I am also generally using Node Red for automation but I have been using the native HA automation system for its calendar trigger functionality. I haven't really played around with getting upcoming calendar events into Node Red.

You're right that there isn't a standalone entity displaying the time of the next loadshedding event. Easiest way to get this is probably by pulling the start time of the next loadshedding event out of the calendar using a template sensor along the lines of:

`{{as_timestamp(states.calendar.loadshedding_local_events.attributes.start_time)}}`

Or if you want something more like a countdown:

`{{as_timestamp(states.calendar.loadshedding_local_events.attributes.start_time) - as_timestamp(now())}}`

You might just need to add some default values in case the templates break when loadshedding is suspended.

Closing this issue since it isn't really related anymore and the original problem was resolved, feel free to open another if needed 👍
