### ISSUE TITLE
can't get area

### ISSUE THREAD

**Issue by cyon30** [swartjean/ha-eskom-loadshedding#29]
## Configuration

```yaml

Add your logs here.

```

## Debug log

```text

Add your logs here.

```

**Comment by swartjean** [comment]
Hi, I have tested on my dev setup with a few different HA versions and confirmed that I can still install and add new areas. A few issues like this have popped up so I'd like to use #31 to track them all and avoid duplicates. Please update that issue with any particulars you can provide.
