### ISSUE TITLE
Unable to add "Area" on new Integration setup  - Full Details

### ISSUE THREAD

**Issue by denzelm5** [swartjean/ha-eskom-loadshedding#31]
Home Assistant : VM
Home Assistant 2023.1.7
Supervisor 2023.01.1
Operating System 9.5
Frontend 20230110.0 - latest

Log Relating to Integration  : 

Logger: homeassistant.helpers.template
Source: helpers/template.py:540
First occurred: 9:34:56 PM (17 occurrences)
Last logged: 9:49:56 PM

Template variable error: 'None' has no attribute 'eskom' when rendering '{{ state_attr('sensor.eskom_loadshedding_stage','status').eskom.stage}}'

Screen Shot : 
![image](https://user-images.githubusercontent.com/57428868/215288011-fb58e927-6a6e-479a-a02f-1ef30d7a0233.png)

 Summary :  
It accepts the API Token successful , at the screen where you have add in your area none of the parameters work. 

Regards
Denzel

**Comment by swartjean** [comment]
Hi, that's an odd one - I double checked in both 2023.1.7 and the latest HA dev build that I can reinstall the integration and select areas with no problem, here is what I get for an input of "ethekwini":

![image](https://user-images.githubusercontent.com/16536996/215317092-e9554b5d-a8b6-4966-81ee-9e724854ae24.png)

Regarding your error of:

> Template variable error: 'None' has no attribute 'eskom' when rendering '{{ state_attr('sensor.eskom_loadshedding_stage','status').eskom.stage}}'

That looks to me like you have a template variable that references `sensor.eskom_loadshedding_stage` which was an old sensor entity before the EskomSePush migration I did a while back. There is no longer a sensor with that name so maybe it is causing some issues.

Could you try disabling/commenting out that template sensor and then reinstalling? I'm not quite sure why it would interfere with the installation at this step but it's all I can think of right now.

**Comment by denzelm5** [comment]
Hi ,

Thanks for your prompt reply. The issue was indeed related to a custom template . This may have came into my configuration after a restore from an older back up.

Thank you very much!

Regards

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
