### ISSUE TITLE
loadshedding_local_status sensor failing to update

### ISSUE THREAD

**Issue by waynetd777** [swartjean/ha-eskom-loadshedding#38]
## Version of the custom_component
1.1.2

## Describe the bug
Starting at 02:12:21 SAST on the morning of 2 October, the loadshedding_local_status sensor is failing to update. The error below is being logged. 

All other sensors are working correctly including the loadshedding_api_quota sensor which indicates that I have not reached my call quota.

I did not apply any updates to my HA setup so the issue is not caused by an HA update.

I tried restarting HA but the problem persists.

## Debug log

```text
Logger: homeassistant
Source: custom_components/eskom_loadshedding/sensor.py:186
Integration: Eskom Loadshedding Interface ([documentation](https://github.com/swartjean/ha-eskom-loadshedding), [issues](https://github.com/swartjean/ha-eskom-loadshedding/issues))
First occurred: 03:40:59 (15 occurrences)
Last logged: 17:41:26

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 233, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 389, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 172, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 469, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 730, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 830, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 774, in _async_generate_attributes
    attr.update(self.extra_state_attributes or {})
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eskom_loadshedding/sensor.py", line 186, in extra_state_attributes
    "Area": info["name"],
            ~~~~^^^^^^^^
KeyError: 'name'
```

**Comment by nicopret1** [comment]
I have the same problem and noticed if I do a query with curl command that my area-id changed. It use to be: westerncape-9-paarl, but it has now changed to: eskme-9-paarldrakensteinwesterncape.

I however cannot find where I can update this detail as the UI don't give me an option to update it and I cannot find in which file this information is stored

**Comment by wimdebruyn** [comment]
> I have the same problem and noticed if I do a query with curl command that my area-id changed. It use to be: westerncape-9-paarl, but it has now changed to: eskme-9-paarldrakensteinwesterncape.  
> 
> I however cannot find where I can update this detail as the UI don't give me an option to update it and I cannot find in which file this information is stored

I had the same problem.  Deleting and reinstalling the integration was easy and quick, and solved the problem.  The sensor names stays the same after a reinstall.

It looks like Eskom changes the area names from time to time.

**Comment by nicopret1** [comment]
> > I have the same problem and noticed if I do a query with curl command that my area-id changed. It use to be: westerncape-9-paarl, but it has now changed to: eskme-9-paarldrakensteinwesterncape.
> > I however cannot find where I can update this detail as the UI don't give me an option to update it and I cannot find in which file this information is stored
> 
> I had the same problem. Deleting and reinstalling the integration was easy and quick, and solved the problem. The sensor names stays the same after a reinstall.
> 
> It looks like Eskom changes the area names from time to time.

Thank you, I did the same and its working again

**Comment by waynetd777** [comment]
I also did the same thing and it is working agian. Thank you @wimdebruyn

**Comment by waynetd777** [comment]
Going to close this out as the post from @wimdebruyn provides a solution.
