### ISSUE TITLE
Area Name Update

### ISSUE THREAD

**Issue by adiweps** [swartjean/ha-eskom-loadshedding#39]
Good day,

Is there a way to update your area? ESP yesterday released new schedules and area names have changed.

**Comment by Dyltong** [comment]
Same here

**Comment by RaidersPlay** [comment]
What I tried. Does not work
Maybe someone else have better luck...

As far as I can figure out `\\HomeAssistant\config\.storage\core.config_entries` needs to be modified.
The variable "area_id" needs to be updated.

The ID can be obtain by going to https://reqbin.com/curl
Run script (from ESP)
`curl --location --request GET 'https://developer.sepush.co.za/business/2.0/areas_search?text=Johannesburg' \
--header 'token:YourID'`

**Comment by Dyltong** [comment]
Under settings, devices and services, eskom integration (http://homeassistant.local:8123/config/integrations/integration/eskom_loadshedding)

I clicked "add entry", used the same API key as before, and then found my area in joburg which had "new" at the end.

I then deleted the old entry. 

This worked.

**Comment by RaidersPlay** [comment]
Might be that the servers are being overloaded at the moment.
After a few retires, I got it to update via the eskom integration guid.
But still waiting for the schedule to update.

Was giving this originally...
![image](https://github.com/swartjean/ha-eskom-loadshedding/assets/58973538/12afcf93-fefa-494b-9b3e-0b8323aa57c6)

**Comment by adiweps** [comment]
> Under settings, devices and services, eskom integration (http://homeassistant.local:8123/config/integrations/integration/eskom_loadshedding)
> 
> I clicked "add entry", used the same API key as before, and then found my area in joburg which had "new" at the end.
> 
> I then deleted the old entry.
> 
> This worked.

This worked, thank you

**Comment by swartjean** [comment]
Apologies for not checking this out, but looks like you came right. Closing this for now.
