### ISSUE TITLE
Not showing up in Intergrations

### ISSUE THREAD

**Issue by denzelm5** [swartjean/ha-eskom-loadshedding#5]
Hi,

Thanks for creating this integration as us South Africans have to plan our lives around Eskom. I downloaded the files and followed the instructions but the "Esksom_Loadshedding_interface" is not appearing under the Integrations .

HA Version :  0.115.3
HACS Version : 1.6.0 
Esksom_Loadshedding_interface Version : 1.0.2

Regards

**Comment by swartjean** [comment]
Hi @denzelm5, thanks for logging an issue 👍 

The recommended way to install this integration is using the Home Assistant Community Store ([HACS](https://hacs.xyz/)) but a manual install should work just fine.

Just to confirm - once you have put the `eskom_loadshedding` folder inside your `custom_components` folder in your Home Assistant directory, you still need to actually add the integration to Home Assistant using the `+` icon on the integration page. The integration won't appear under your installed integrations automatically.

If the integration isn't showing up in the `Set up a new integration` menu, then it might be a problem with the directory structure. You should have something like this:

```
homeassistant
|
| - configuration.yaml
| - automations.yaml
| - ...
| - custom_components
  | - eskom_loadshedding
    | - __init__.py
    | - eskom_interface.py
    | - ...
```

**Comment by denzelm5** [comment]
Hi Jean,

Thanks for your reply. I use the HACS to install the integration, it just took a while to appear but all good now.

Thanks!

Regards
Denzel Marimuthu

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by swartjean** [comment]
Great! Thanks for the feedback @denzelm5 👍
