### ISSUE TITLE
Schedules

### ISSUE THREAD

**Issue by tiaanv** [swartjean/ha-eskom-loadshedding#7]
This is not so much a feature request as it is a question.

The status sensor is great, but of course, the holy grail is being able to have the schedule on hand, and perhaps augment the current sensor stack with a few potential sensors:

- Next Load shedding (DateTime)
- Load shedding Active (True/False)

I have been thinking of writing this for some time, but have been too lazy to calculate an algorithm or capture the schedules.  Obviously for this to be generic, there can be multiple schedules municipal and Eskom...

The goal is to have a feature set in HA, similar to ESPush or LoadsheddingNotifier.

Just wondered if you have put any effort into this.

**Comment by tiaanv** [comment]
Doh.  Saw you already covered this in #6 .

However... being a COCT customer Eskom Shedule would not apply, and the API of course is not going to give that data...  Perhaps this is not appropriate for the Integration in general.

**Comment by tiaanv** [comment]
@swartjean 
I have made an attempt to integrate the COCT loadshedding schedule into your sensor... I hacked my way around the existing integration a bit, as I have zero experience in writing an integration.  The implementation is not correct, as it generated multiple devices (one for each sensor)... I think this should really be one device with multiple sensors... there is also the option of adding a bunch of attributes to the sensors..

I created a fork of your code.  Feel free to integrate it into yours (more elegantly) should you want to do so.
https://github.com/tiaanv/ha-eskom-loadshedding

The actual functions I used was not my work... another bit of dev work written in Java
https://github.com/Quantiversal/Cape-Town-Loadshedding-Schedule

I just wrote an appropriate python version of it. Almost function for function.

Work is not complete yet, but it works.

**Comment by cschutte** [comment]
Thanks Tiaan - works well for COCT schedules!

**Comment by tiaanv** [comment]
> Thanks Tiaan - works well for COCT schedules!

@cschutte  with us having a fair amount of load-shedding in the last few days I have had some time to test.  There are one or two bugs, that I have since ironed out.  I will update Github soon.

**Comment by cschutte** [comment]
Thanks @tiaanv . I do get this error sometimes: "Error fetching eskom_loadshedding data: hour must be in 0..23", and then it does not update. Hopefully that is one of the issues you already saw?

**Comment by tiaanv** [comment]
Jip… That’s one of them. Fixed.

**Comment by tiaanv** [comment]
@cschutte Github updated with Fixes. Until @swartjean decides if he wants to integrate this into the original Integration, please go ahead and log any issues you discover, or feature requests at my fork: [https://github.com/tiaanv/ha-eskom-loadshedding](https://github.com/tiaanv/ha-eskom-loadshedding).

**Comment by swartjean** [comment]
I'm closing this issue, @tiaanv thanks for taking the integration further with the CoCT schedules and apologies for not following up on this. I've moved in a different direction and integrated with the EskomSePush API.
